# file postgresql-service.yml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: urbalurba
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None
