# file: common/shared-config/global-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: urbalurba
data:
  POSTGRES_USER: postgres
  DATABASE_NAME: urbalurba_db
  DATABASE_USERNAME: strapi
# push to kubernetes using: microk8s kubectl apply -f common/shared-config/global-configmap.yml